server:
  port: 8083
people:
  name: 123456@yll.yll
  age: 18
  happy: false
  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
  maps:
    k1: v1
    k2: 12
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12